language:
- nix

script:
- nix-shell --pure --command 'cd src; make all'

before_deploy:
- git config --local user.name "Igal Tabachnik"
- git config --local user.email "hmemcpy@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG

cache:
  directories:
    src/_minted-ctfp

deploy:
  - provider: releases
    api_key:
      secure: usNWQZc/HcrZxR72+Qz2YXeyf56h0EwLVl6oOXIivxTWQCTTQ0cE6tXG6lP8JxQ1qlfAhbdh4QOmz6jxQD60HxsUwDWmt9t51o+8n3EMeID0hc45ES40/mbieUfR1jbkLbwmL16Z/bWsvUErmGuUgOxYrUCplK9fWs7Vvt8xmReFdunw8XpVrywG4rl1jXDo9YWihMps5KLOqd3mY3yvlxAmB+UKkhHPNdcEuEghEBhC8HZoZkFiwfRw/8PeOh9VpnQ2ht9eDXOlB7zNYY9Xr/S98FbzfZXxFjApXVRgNP8k2UYyHn8HCmIoCSs+Jv06tEvNCuwTvj0JNsuoW7vu/Q7wrrpScfDL+WnSw2CScml+xAe7Q4caoZKkzaMCnj5fHbPEZ731+SLZNbG6TMTYhMqhFm0Fr87bwdNlayqAssIhOwU4ca3pnZOQFO4vNOWblNfbHsX5F9sJDOR0uD4Y+PgfNWgTsssXqei7owBJNTe+qz5Q7IaFA3A8EMp57CV1dUCgmjxVuugtz6DLpl16WGiWpqakIA900GXMG+2c4ENCCDWmYtGlpWs2lSBqRYHV1gncE8UGtIih8G6g5jQd2aJUQKHKuaEiv/28WLI7f2exUuOBmc0ce4xP+qZAs5XWiPo4jJLNyb81uNIZ0jCb/c5+lEH8EsYF+jFOrmw17GQ=
    file: out/**/*.pdf
    file_glob: true
    skip_cleanup: true
    on:
      repo: hmemcpy/milewski-ctfp-pdf
      branch: master
      tags: true
  - provider: s3
    bucket: milewski-ctfp-pdf
    access_key_id: '$ARTIFACTS_KEY'
    secret_access_key: '$ARTIFACTS_SECRET'
    region: us-east-1
    acl: public_read
    local_dir: out
    skip_cleanup: true
    on:
      all_branches: true
      repo: hmemcpy/milewski-ctfp-pdf