language:
  - nix

script:
  - nix-shell --pure --command 'cd src; make'

deploy:
  - provider: s3
    bucket: milewski-ctfp-pdf
    access_key_id: '$ARTIFACTS_KEY'
    secret_access_key: '$ARTIFACTS_SECRET'
    region: us-east-1
    acl: public_read
    local_dir: out
    skip_cleanup: true
    on:
      all_branches: true
      repo: hmemcpy/milewski-ctfp-pdf
  - provider: releases
    api_key:
      secure: XIHB7JJMi1+VcoiIfCPxJ+XsTQZ1xG17VXJ0xrHma2PsQhGtT0vK/rdRE1wAjw1kwEKGe6fP6cVf36QPBA8EuUJYN2pU27AUTB0Wp6aZ1kmaY/cIsyMo340qXQnB28o9clIzufn7ouuiEjgCCAahAvweAsYf/mv6EpZTzl3UAD/WrryyaabfEsiR+6Am0mw+r1zeXXiiappA4rLHjdBgTnF6AXZf/fKzwEm53vIjzcVOTrqIaPCevvf0UUP1D4iD435jov7my7ZZc6zGEwUoDeuKthk3xFmQ5e7gw0FvjUXyqhjOQmc5myX8XSfzG4SlY8jmz9bgFyKTPB1sja8lV738N2HN0tfY9HcCQDXCLCOSJOtEa833p5rIhfHnKy0gQw3K9LvOQnMjiM/0Ik9uWuYIAQW1rtnI8iPClEF8hXshXewGNU+WmxGfQ82OYey8wHPXg4FZj50p7djFr2l0GLG4ngbrFcp9U9msXCVVDDa+0vO09LpGZ6WDWYH4inaK4catJT8vrfSprx1BbiJG+EuzjgvTFKNoxydTiM4EYW3QkVTRkUCa2ZO7ARg5caT0fL12csHGBXlPN3L5RWnTIHg8mWmz3jzBWYKs3IFLMvwKPF3y4Gbq7Ippmj9OwSyR7/V8ozNux5Wb8mFyPdFaW0PsU1SqdNpEy0ry7yFptWI=
    file:
      out/category-theory-for-programmers.pdf
      out/category-theory-for-programmers-scala.pdf
    skip_cleanup: true
    on:
      repo: hmemcpy/milewski-ctfp-pdf
      tags: true
